setGeneric("manufacturer",function(object) standardGeneric("manufacturer"))
setGeneric("manufacturer<-", function(object, value) standardGeneric("manufacturer<-"))
setGeneric("bothStrands", function(object) standardGeneric("bothStrands"))
setGeneric("allele", function(object, allele, strand) standardGeneric("allele"))
setGeneric("getM", function(object) standardGeneric("getM"))
setGeneric("getA", function(object) standardGeneric("getA"))


setGeneric("calls<-", function(object, value) standardGeneric("calls<-"))
setGeneric("calls", function(object) standardGeneric("calls"))
setGeneric("confs", function(object) standardGeneric("confs"))
setGeneric("confs<-", function(object, value) standardGeneric("confs<-"))
setGeneric("callsConfidence", function(object) standardGeneric("callsConfidence"))
setGeneric("callsConfidence<-", function(object, value) standardGeneric("callsConfidence<-"))
setGeneric("cnConfidence", function(object) standardGeneric("cnConfidence"))
setGeneric("cnConfidence<-", function(object, value) standardGeneric("cnConfidence<-"))
setGeneric("copyNumber", function(object) standardGeneric("copyNumber"))
setGeneric("copyNumber<-", function(object, value) standardGeneric("copyNumber<-"))
setGeneric("chromosome", function(object) standardGeneric("chromosome"))
setGeneric("chromosome<-", function(object, value) standardGeneric("chromosome<-"))
setGeneric("db", function(object) standardGeneric("db"))
setGeneric("kind", function(object) standardGeneric("kind"))
setGeneric("position", function(object) standardGeneric("position"))
setGeneric("isSnp", function(object) standardGeneric("isSnp"))

setGeneric("CA", function(object) standardGeneric("CA"))
setGeneric("CB", function(object) standardGeneric("CB"))
setGeneric("CA<-", function(object, value) standardGeneric("CA<-"))
setGeneric("CB<-", function(object, value) standardGeneric("CB<-"))
setGeneric("emissionPr", function(object) standardGeneric("emissionPr"))
setGeneric("emissionPr<-", function(object, value) standardGeneric("emissionPr<-"))
setGeneric("rangedData", function(object) standardGeneric("rangedData"))
setGeneric("rangedData<-", function(object, value) standardGeneric("rangedData<-"))
setGeneric("segmentData", function(object) standardGeneric("segmentData"))
setGeneric("segmentData<-", function(object, value) standardGeneric("segmentData<-"))

setGeneric("genomeBuild", function(object) standardGeneric("genomeBuild"))
setGeneric("geometry", function(object) standardGeneric("geometry"))
